# Generated by Django 5.2.5 on 2025-09-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_managers_alter_appuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='tutor',
        ),
    ]
