# Generated by Django 5.2.5 on 2025-09-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='phone_number',
        ),
    ]
