# Generated by Django 5.2.5 on 2025-09-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_appuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='middle_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
