# Generated by Django 5.2.5 on 2025-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_middle_name_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
