# Generated by Django 5.2.5 on 2025-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_appuser_full_name_alter_appuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
    ]
